### ISSUE TITLE
MemoryError in palantir.io.from_10x()

### ISSUE THREAD

**Issue by zezhuo** [ManuSetty/Palantir#4]
MemoryError occurs when reading 10x Genomics data using from_10x() function.

-python --version
3.7

**Comment by ManuSetty** [comment]
What is the dataset you are trying to use and how much memory do you have on your computer?

**Comment by zezhuo** [comment]
I am trying to read barcodes.tsv, genes,tsv, and matrix.mtx using from_10x() function. The memory of my computer is 128 GB. 

I guess this error is related to :

dataMatrix = pd.DataFrame(dataMatrix.todense(),
                              columns=cell_names, index=gene_names)

Thanks!

**Comment by ManuSetty** [comment]
What is the size of the dataMatrix?

Manu

**Comment by zezhuo** [comment]
For the matrix.mtx, it is 121,353 KB.

**Comment by ManuSetty** [comment]
I meant the shape of the matrix: dataMatrix.shape

Manu

**Comment by zezhuo** [comment]
About 5000 cells and 20,000 genes.

**Comment by ManuSetty** [comment]
I am surprised you would get memory error for this matrix. Please make sure
to use the filtered output from 10X. I would also suggest using the scanpy
interface to load the data, filter and export to csv and use this csv as
input to Palantir.

**Comment by zezhuo** [comment]
Thanks for your suggestions. 
I have got the solution. Don't know why 32bit python was default version when downloaded in python.org. I reinstall python3.7 64bit, and the problem is solved.
Sorry for the stupid question.
Nelson
