### ISSUE TITLE
run_palantir issues

### ISSUE THREAD

**Issue by wy-18** [ManuSetty/Palantir#5]
Dear Dr. Setty,

Thank you very much for this package, we would like to use it to analyze our data.  I got an error after I reinstalled the anaconda.

The code produced the error:
pr_res = palantir.core.run_palantir(pt.ms_data, start_cell, num_waypoints=pt.counts.shape[0]//10, n_jobs=10)

The screenshot of the error:
![image](https://user-images.githubusercontent.com/52818723/61355776-9c7db680-a8a7-11e9-8909-0c67b60a2d90.png)
![image](https://user-images.githubusercontent.com/52818723/61355799-aa333c00-a8a7-11e9-94e4-ad2a7ef97a34.png)
![image](https://user-images.githubusercontent.com/52818723/61355811-b3bca400-a8a7-11e9-836d-bd77577d2791.png)

Before reinstallation, Palantir was woking good, but I saw a warning that might be related to this keyerror:

![image](https://user-images.githubusercontent.com/52818723/61356014-0bf3a600-a8a8-11e9-829b-d8c97e1db651.png)

Could you please help us to figure out what gets wrong?

Thank you!
Cathy

**Comment by ManuSetty** [comment]
Thank you for your interest in Palantir. Can you please send me the versions python and the various packages that are being used? 

One other thing to try is to change the index names of the data to strings. For example:
```norm_df.index = norm_df.index.astype(str)```

**Comment by wy-18** [comment]
Dear Dr.Setty,

Thank you very much for the reply, I tried your suggestion and got a different error.
The code I added is 
`pt.ms_data.index = pt.ms_data.index.astype(str)` 
and the error is 
![image](https://user-images.githubusercontent.com/52818723/61383290-f77fcf80-a8e0-11e9-8e1a-cdb9efff364b.png)

The follow are my packages' versions:
Python version is 3.6.5
pandas version is '0.24.0rc1'
numpy version is '1.14.3'
matplotlib version is '2.2.2'
seaborn version is '0.8.1'

Thank you,

Cathy

**Comment by ManuSetty** [comment]
Sorry, forgot to mention this earlier. This repo is not uptodate. Can you try version here: https://github.com/dpeerlab/Palantir ?

**Comment by wy-18** [comment]
Dear Dr. Setty,

The version of Palantir I installed is '0.2.1', which is the most updated one. I tried to reinstall Palantir, but I got same error.

![image](https://user-images.githubusercontent.com/52818723/61439273-cb615e80-a973-11e9-8cd2-0235ed30743c.png)

I think this issue might be related to updates of pandas ? (but I also have tried different versions of pandas, which still didn't work for me)

Bests,

Cathy

**Comment by ManuSetty** [comment]
What is the ``pt`` object you are assigning ms_data too? Do you subset the data in any manner after normalization but before Palantir ?

**Comment by wy-18** [comment]
Dear Dr. Setty,

We use  `pt` object to save the palantir variables. Here is the type and a part of pt.ms_data:
![image](https://user-images.githubusercontent.com/52818723/61459839-33c63500-a9a0-11e9-9b02-6b53d26839ad.png)
 
The followings are how we define this class:
![image](https://user-images.githubusercontent.com/52818723/61460054-961f3580-a9a0-11e9-86a0-93e62b0d92f4.png)
![image](https://user-images.githubusercontent.com/52818723/61460082-a1726100-a9a0-11e9-96bc-badd6ec00129.png)
![image](https://user-images.githubusercontent.com/52818723/61460412-4725d000-a9a1-11e9-99f2-ccf1e5a3b644.png)
![image](https://user-images.githubusercontent.com/52818723/61460236-ea2a1a00-a9a0-11e9-8b79-fba432bb9655.png)

Thank you,

Cathy

**Comment by ManuSetty** [comment]
Thank you for sharing this.

I think the issue is because of the row names and the code is getting tripped up between integers and strings. 

Can you please try changing the row names to strings at the very beginning of the analysis. This could be something along the lines of 

```
counts = pd.read_csv(....)
counts.index = ['Cell_' + str(i) for i in counts.index
```

This should hopefully avoid any confusion between string and integer indexes.

**Comment by wy-18** [comment]
Yes, this issue has been solved, thank you very much!

Cathy

**Comment by wy-18** [comment]
Dear Dr. Setty,

I got your idea of changing the row names to strings
![image](https://user-images.githubusercontent.com/52818723/61626261-66797180-acaf-11e9-965c-61398d2a5b1d.png)
but I still got an error like this
![image](https://user-images.githubusercontent.com/52818723/61628025-c07c3600-acb3-11e9-8c70-6b7df1b58a5b.png)
![image](https://user-images.githubusercontent.com/52818723/61628038-c83bda80-acb3-11e9-8fa9-4c00ba13a9dc.png)
Do you have any thoughts of what I could do?

Thank you!

Cathy

**Comment by ManuSetty** [comment]
Do you have duplicate row names by any chance in the counts data frame?

Manu

**Comment by wy-18** [comment]
Thank you, I figured it out by changing them just before analysis.

Cathy
